name: Sync Mastodon

on:
  workflow_dispatch:
  schedule:
    - cron: "17 10 * * *"  # 10:17 UTC every day -> 05:17 EST / 06:17 EDT

jobs:
  copy-mastodon-helm-chart:
    name: Copy Mastodon Helm Chart
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Mastodon repo
        uses: actions/checkout@v3
        with:
          repository: mastodon/chart
          path: mastodon-chart

      - name: Checkout our repo
        uses: actions/checkout@v3
        with:
          path: helm-charts

      - name: Copy Helm Chart
        run: |
          mkdir -p helm-charts/charts/mastodon  # ensure the directory exists
          cp -r mastodon-chart/* helm-charts/charts/mastodon/

      - name: Apply patches
        working-directory: helm-charts
        run: |
          readarray -d '' entries < <(printf '%s\0' patches/mastodon/*.patch | sort -zV)
          for entry in "${entries[@]}"; do
            echo "Applying patch: $entry"
            git apply "$entry"
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          path: helm-charts
          branch-suffix: short-commit-hash
          commit-message: "Sync Mastodon Helm Chart"
          title: "Sync Mastodon Helm Chart"
          body: "Sync Mastodon Helm Chart"
          labels: "dependencies"
          reviewers: "tizz98"
          assignees: "tizz98"
